### ISSUE TITLE
Persistence Length of Polymer error using MDAnalysis

### ISSUE THREAD

**Issue by Karpurmanjari** [Karpurmanjari/Issues#1]
Hi MDA developers,

I am new to Python and MDA, I tried using the following code to determine the persistence length of the polymer. I used the following code -
import MDAnalysis as mda
from MDAnalysis.analysis import polymer
from matplotlib import pyplot as plot

u = mda.Universe('md3.tpr', 'md3.gro')

gel = u.select_atoms('name N CA C O')
ethanol = u.select_atoms('name C O H')
PL = polymer.PersistenceLength([gel])
PL.run()
PL.perform_fit()
PL.plot()

print(ethanol.atoms)
print(gel.atoms)

PL = polymer.PersistenceLength([gel])

print(PL)

and I got the following error-

<pre>OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
&lt;AtomGroup [&lt;Atom 5: C of type C of resname GL, resid 0 and segid seg_0_GL&gt;, &lt;Atom 11: O of type O of resname GL, resid 0 and segid seg_0_GL&gt;, &lt;Atom 14: H of type H of resname GL, resid 0 and segid seg_0_GL&gt;, ..., &lt;Atom 148528: H of type H of resname ETH, resid 16004 and segid seg_1_ETH&gt;, &lt;Atom 148529: H of type H of resname ETH, resid 16004 and segid seg_1_ETH&gt;, &lt;Atom 148530: H of type H of resname ETH, resid 16004 and segid seg_1_ETH&gt;]&gt;
&lt;AtomGroup [&lt;Atom 1: N of type N of resname GL, resid 0 and segid seg_0_GL&gt;, &lt;Atom 2: CA of type CA of resname GL, resid 0 and segid seg_0_GL&gt;, &lt;Atom 5: C of type C of resname GL, resid 0 and segid seg_0_GL&gt;, ..., &lt;Atom 148522: C of type C of resname ETH, resid 16004 and segid seg_1_ETH&gt;, &lt;Atom 148523: C of type C of resname ETH, resid 16004 and segid seg_1_ETH&gt;, &lt;Atom 148524: O of type O of resname ETH, resid 16004 and segid seg_1_ETH&gt;]&gt;
&lt;MDAnalysis.analysis.polymer.PersistenceLength object at 0x7efeb35eb510&gt;
</pre>

I am not able to understand whats happening.

**Comment by orbeckst** [comment]
The  place to ask  questions about MDAnalysis is the MDAnalysis user list https://groups.google.com/group/mdnalysis-discussion ; the developers read it and try to answer, and many knowledgeable users help, too.

If it looks as if this is a bug in MDAnalysis then we will ask you to open an issue in the MDAnalysis issue tracker https://github.com/MDAnalysis/mdanalysis/issues/.
